---
ID: "03724cb3-a985-4727-9fc2-e3de02a44256"
Parent: "0687fd7e-5de0-4305-b84e-1d4ab862ec89"
Template: "0687fd7e-5de0-4305-b84e-1d4ab862ec89"
Path: /sitecore/templates/Project/JumpStart/Page Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {5577F579-613B-4A5C-9F00-E9DFD5B25BD9}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230915T145744Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\martin.miles@perficient.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\martin.miles@perficient.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "be8cbab3-b61c-4373-a1a1-3d1e9d685db9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\martin.miles@perficient.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230915T145745Z
